name: Build
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  workflow_dispatch: { }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Change wrapper permissions
        run: chmod +x gradlew
      - name: Run tests
        run: ./gradlew test
      - name: Build Debug APK
        run: ./gradlew assembleRelease
        run: cp app/build/outputs/apk/release/*.apk ./
      - uses: actions/upload-artifact@v3
        with:
          name: Apk save
          path: app/build/outputs/apk/release/app-release.apk
      - uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: '**/build/reports/tests/'